### ISSUE TITLE
Make it compatible with .Net Core

### ISSUE THREAD

**Issue by fanoI** [nathanpjones/DecimalMath#2]
Visual Studio 2015 says that "Decimal" is not defined and that a reference to mscorlib.dll will solve the issue but then the adding of the reference is not accepted (but of Net Core?).

In any case Decimal is defined in Net Core and could normally used so there should be some incompatibilities with this library.

**Comment by fanoI** [comment]
The problem was partly solved using the compatibility library "Microsoft.NETCore.Portable.Compatibility" but it will be better if it will compiled without issues.

**Comment by monty241** [comment]
I have migrated it to 2.0, see commit https://github.com/nathanpjones/DecimalMath/commit/96d228ff27acbd260285a2210d9cf0ecfc54f150.

Once VS2017 pull request has been integrated, I will upload that one.

**Comment by fanoI** [comment]
I've to say that at least with the arrive of Net Standard 2.0 things are becoming better, this library is now loaded correctly and only a warning is shown.
However making it totally compatible with Net Core it will be better.
