### ISSUE TITLE
Debug writes too expensive

### ISSUE THREAD

**Issue by scidec** [nathanpjones/DecimalMath#9]
Awesome library, but had to remove line 120 (from DecimalExTrig.cs) so as not to log. This line caused sin functions to be so slow in complex routines that debugging them was impossible. In the end I just removed all refs to system diagnostics and included the modified extension files locally.

Debug.WriteLine("{0:000}:{1,33:+0.0000000000000000000000000000;-0.0000000000000000000000000000} ->{2,33:+0.0000000000000000000000000000;-0.0000000000000000000000000000}",
                    doubleIteration / 2, nextAdd, result + nextAdd);

**Comment by nathanpjones** [comment]
Oo, that's a good point. I'll revise these to be hidden behind a compiler directive so they aren't included in the package builds.
